config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  resources :user_stocks, except: [:show, :edit, :update]
  resources :users, only: [:show]
  resources :friendships
  
  mount ActionCable.server => '/cable'

  resources :chatrooms, param: :id, except: [:index]
  resources :messages

  root 'home#index'
  get 'my_portfolio', to: "users#my_portfolio"
  get 'search_stocks', to: "stocks#search"
  get 'my_friends', to: "users#my_friends"
  get 'search_friends', to: "users#search"
  post 'add_friend', to: "users#add_friend"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
  validates :topic, presence: true, uniqueness: true, case_sensitive: false
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
  establish_connection :legacy
  self.table_name = "product"
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks
  
  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
  
  def self.new_from_lookup(ticker_symbol)
    looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
    new(name: looked_up_stock.company_name, ticker: looked_up_stock.symbol, last_price: looked_up_stock.latest_price)
  end
  
  def self.strip_commas(number)
    number.gsub(",", "")   
  end
  
end

app/models/test.rb
class Test < ApplicationRecord
  self.table_name = "test"
end

app/models/user.rb
class User < ApplicationRecord
  scope :active_users, -> { where.not(confirmed_at: nil) }
  scope :unconfirmed_users, -> { where(confirmed_at: nil) }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :messages
  has_many :chatrooms, through: :messages

  validates_presence_of :first_name, :last_name, :email

  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end
  
  
  def stock_already_added?(ticker_symbol)
    stock = Stock.find_by_ticker(ticker_symbol)
    return false unless stock
    user_stocks.where(stock_id: stock.id).exists?
  end
  
  def under_stock_limit?
    (user_stocks.count < 10)
  end
  
  def can_add_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_added?(ticker_symbol)
  end
  
  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end
  
  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end
  
  def self.search(param)
    param.strip!
    param.downcase!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end
  
  def self.first_name_matches(param)
    matches('first_name', param)
  end
  
  def self.last_name_matches(param)
    matches('last_name', param)
  end
  
  def self.email_matches(param)
    matches('email', param)
  end
  
  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :get_chat_rooms

  def after_sign_in_path_for(resource)
    my_portfolio_path
  end
  
  def get_chat_rooms()
    @chatrooms = Chatroom.all
    @message = Message.new
  end

end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatrooms = Chatroom.all
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new

    if params[:id].blank?
      flash.now[:danger] = "Chat with that name doesn't exist"
    end

    respond_to do |format|
      format.js { render partial: 'chatrooms/show' }
    end
  end

  def new
    @chatroom = Chatroom.new
  end
  
  def create
    @chatroom = current_user.chatrooms.build(chat_room_params)
    if @chatroom.save
      flash[:success] = 'Chat room added!'
      redirect_to my_portfolio_path
    else
      render 'new'
    end
  end

  def chat_room_params
    params.require(:chatroom).permit(:topic)
  end

  def destroy
    @chatroom = Chatroom.find(params[:id])
    @chatroom.destroy
    flash[:notice] = "Chatroom was successfully removed"
    redirect_to my_portfolio_path
  end 
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def destroy
    @friendship = current_user.friendships.where(friend_id: params[:id]).first
    @friendship.destroy
    flash[:notice] = "Friend was successfully removed"
    redirect_to my_friends_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    message = Message.new(message_params)
    message.user = current_user
    if message.save
      ActionCable.server.broadcast 'messages',
        message: message.body,
        user: message.user.full_name
      head :ok
    end
  end

  private

    def message_params
      params.require(:message).permit(:body, :chatroom_id)
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  
  def search
    if params[:stock].blank?
      flash.now[:danger] = "You have entered an empty search string"
    else
      @stock = Stock.new_from_lookup(params[:stock])
      flash.now[:danger] = "You have entered an incorrect symbol" unless @stock
    end
    respond_to do |format|
      format.js { render partial: 'users/result' }
    end
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
  
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.find_by_ticker(params[:stock_ticker])
    if stock.blank?
      stock = Stock.new_from_lookup(params[:stock_ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:success] = "Stock #{@user_stock.stock.name} was successfully added to portfolio"
    redirect_to my_portfolio_path
  end
  
  def destroy
    stock = Stock.find(params[:id])
    @user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    @user_stock.destroy
    flash[:notice] = "Stock was successfully removed from portfolio"
    redirect_to my_portfolio_path
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @user_stocks = current_user.stocks
  end

  def my_friends
    @friendships = current_user.friends
  end
  
  def show
    @user = User.find(params[:id])
    @user_stocks = @user.stocks
  end

  def search
    if params[:search_param].blank?
      flash.now[:danger] = "You have entered an empty search string"
    else
      @users = User.search(params[:search_param])
      @users = current_user.except_current_user(@users)
      flash.now[:danger] = "No users match this search criteria" if @users.blank?
    end
    respond_to do |format|
      format.js { render partial: 'friends/result' }
    end
  end

  def add_friend
    @friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: @friend.id)
    if current_user.save
      flash[:notice] = "Friend was successfully added"
    else
      flash[:danger] = "There was something wrong with the friend request"
    end  
    redirect_to my_friends_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/views/chatrooms/_index.html.erb
<button type="button" class="btn btn-info btn-md showChat" data-toggle="modal" data-target="#myModal">Open Chat Window</button>

<div class="modal" id="myModal" data-backdrop="false">
  <div class="modal-content">
    <div class="modal-header modal-body modal-footer">
      <button type="button" class="close closeChat" data-dismiss="modal">&times;</button>
      <table>
        <tr>
          <th>
            <div id="chat-frame">
              <%= render 'chatrooms/show' %>
            </div>
          </th>
          <th class = "test">
            <div class="col-md-4 panel-chatrooms">
              <p class="lead"><%= link_to 'New chat room', new_chatroom_path, class: 'btn btn-xs btn-primary' %></p>
              <% if @chatrooms %>
                <ul>
                  <% @chatrooms.each do |chat| %>   
                    <li style = "list-style-type: none">
                      <strong><%= chat.topic %></strong>
                      <%= link_to "Enter", chatroom_path(chat),remote: true , class: 'btn btn-xs btn-primary' %>
                      <%= link_to "Delete this chatroom", chatroom_path(chat), 
                                        method: :delete,
                                        data: {confirm: "Are you sure?"}, 
                                        class: "btn btn-xs btn-danger" %>
                    </li>
                  <% end %>
                </ul>
              <% end %>
            </div>          
          </th>
        </tr>
    </table>
  </div>
</div>

app/views/chatrooms/_show.html.erb
<% if @chatroom %>
  <div class="row col-md-12 panel-body">
    <h3><%= @chatroom.topic %></h3>
    <div class="panel panel-default">
      <% if @chatroom.messages.any? %>
        <div class="panel-chat" id="messages">
          <%= render partial: 'messages/message', collection: @chatroom.messages%>
        </div>
      <%else%>
        <div class="panel-body hidden" id="messages">
        </div>
      <%end%>
    </div>
    <%= render partial: 'messages/message_form', locals: {message: @message, chatroom: @chatroom}%>
  </div>
<% end %>

app/views/chatrooms/_show.js.erb
$("#chat-frame").html("<%= j (render 'chatrooms/show.html') %>")

app/views/chatrooms/new.html.erb
<h1>Add chat room</h1>

<%= form_for @chatroom do |f| %>
  <div class="form-group">
    <%= f.label :topic %>
    <%= f.text_field :topic, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

app/views/chatrooms/show.html.erb
<div class="row col-md-8 col-md-offset-2">
  <h1><%= @chatroom.topic %></h1>

<div class="panel panel-default">
  <% if @chatroom.messages.any? %>
    <div class="panel-body" id="messages">
      <%= render partial: 'messages/message', collection: @chatroom.messages%>
    </div>
  <%else%>
    <div class="panel-body hidden" id="messages">
    </div>
  <%end%>
</div>

  <%= render partial: 'messages/message_form', locals: {message: @message, chatroom: @chatroom}%>
</div>

app/views/home/index.html.erb
<h1>Welcome to my portfolio Stock tracker</h1>
<div>
  <h3>
    Hello as tryout i wrote simple stock-tracking app<br/>
    It functions as a strock tracking social app<br/>
    <br/>
    App allows You to:
    <ul>
      <li>Track stock prizes searched by Ticker</li>
      <li>Add up to 10 stocks to your portfolio</li>
      <li>Search for friends</li>
      <li>Create chatRooms & chat in real time with other Users</li>
    </ul>
    <div class="container">
      There are two TEST accounts:<br>
      email: 1484313@gmail.com<br>
      email: aaa@wp.pl<br>
      password: password<br>
    </div>
    Use button 'Sign in' for testing
    <%= link_to('Sign In', new_user_session_path, class: 'btn btn-md btn-primary', title: 'Sign In') %>
    <a target="_blank" rel="noopener noreferrer" href="https://github.com/devkamilgrzybek/rails-finance-tracker", class="btn btn-md btn-success" >GitHub</a>    
  </h3>
</div>

app/views/messages/_message.html.erb
<p>
  <b><%= message.user.full_name %></b>: <%= message.created_at %><br>
  <%= message.body %>
</p>

app/views/messages/_message_form.html.erb
<%= form_for message, remote: true, authenticity_token: true do |f| %>
  <%= f.text_area :body, class: "form-control", data: {textarea: "message"}, class: "col-md-8" %>

  <%= f.hidden_field :chatroom_id, value: chatroom.id %>
  <%= f.submit "send", class: "btn btn-primary test", data: {send: "message"} %>
<% end %>

app/views/stocks/_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Current Price</th>
      <% if @user.id == current_user.id %>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @user_stocks.each do |user_stock| %>
      <tr>
        <td><%= user_stock.name %></td>
        <td><%= user_stock.ticker %></td>
        <td><%= user_stock.last_price %></td>
        <% if @user.id == current_user.id %>
          <td><%= link_to "Delete this stock", user_stock_path(user_stock), 
                      method: :delete,
                      data: {confirm: "Are you sure?"}, 
                      class: "btn btn-xs btn-danger" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_result.html.erb
<% if @stock %>
  <div class="well results-block">
    <strong>Symbol: </strong> <%= @stock.ticker %>
    <strong>Name: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.last_price %>
  </div>
  <% if current_user.can_add_stock?(@stock.ticker) %>
    <%= link_to "Add to my stocks", 
        user_stocks_path(user: current_user, stock_ticker: @stock.ticker),
                                class: "btn btn-xs btn-success", method: :post %>
  <% else %>
    <span class="label label-default">
      Stock cannot be added because you have already added
      <% if !current_user.under_stock_limit? %>
        10 stocks
      <% end %>
      <% if current_user.stock_already_added?(@stock.ticker) %>
        this stock
      <% end %>
    </span>
  <% end %>
<% end %>

app/views/users/_result.js.erb
$('#results').html("<%= j (render 'users/result.html') %>")

app/views/users/my_friends.html.erb
<%= render 'friends/lookup' %>

<% if @friendships.size > 0 %>
<table class="table table-striped">
  <thead>
    <tr>
      <th colspan="3" class="page-header">
        <h2>My Friends</h2>
      </th>
    </tr>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @friendships.each do |friend| %>
      <tr>
        <td><%= friend.full_name %></td>
        <td><%= friend.email %></td>
        <td>
          <%= link_to "View Profile", user_path(friend), class: "btn btn-primary btn-xs" %>
          <%= link_to "Remove Friend", friendship_path(friend), method: :delete,
            data: { confirm: "Are you sure?" }, class: "btn btn-xs btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>  
<% else %>
  <div class="row col-lg-12">
    <p class="lead">
      You don't have any friends yet, please add some!
    </p>
  </div>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<h3>Search for Stocks</h3>
<div id="stock-lookup">
  <%= form_tag search_stocks_path, remote: true, method: :get, 
                          id: "stock-lookup-form" do %>
    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-10">
        <%= text_field_tag :stock, params[:stock], 
                          placeholder: "Stock ticker symbol", 
                          autofocus: true,
                          class: "form-control search-box input-lg" %>
      </div>
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
          <i class="fa fa-search"></i> Look up a stock
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="results">
  <%= render 'users/result' %>
</div>

<%= render 'stocks/list' %>

app/views/users/show.html.erb
<h2>User Details</h2> 

<dl class="dl-horizontal"> 
  <dt><strong>Full Name</strong></dt> 
  <dd><%= @user.full_name %></dd> 
  <dt><strong>Email</strong></dt> 
  <dd><%= @user.email %></dd> 
</dl> 

<% if @user.stocks.size > 0 %> 
  <%= render 'stocks/list' %> 
<% else %> 
  <p class="lead">This user is not tracking any stocks</p> 
<% end %> 

<%= link_to "Back", my_friends_path, class: "btn btn-primary" %>